ON SHUTDOWN

DO WHILE TYPE("_SCREEN.ACTIVEFORM")="O" AND NOT NULL(_SCREEN.ACTIVEFORM)
	_SCREEN.ACTIVEFORM.RELEASE
	DOEVENTS FORCE
ENDDO

DO WHILE TYPE("_SCREEN.FORMS(1)")="O" AND NOT NULL(_SCREEN.FORMS(1))
	_SCREEN.FORMS(1).RELEASE
	DOEVENTS FORCE
ENDDO

CLEAR EVENTS
SET SYSMENU TO defa
cancel
*QUIT
